name: CI/CD pipelines

# Send a request to access:
#     https://github.com/sir-farfan/litt/
# in order to watch the pipelines

on: [push, workflow_dispatch]

jobs:
  quality:
    name: Quality
    runs-on: debian-latest
    container: golangci/golangci-lint:v1.34.1
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run linter for code quality
        run: |
          golangci-lint run -v --timeout 3m0s

  build:
    name: Build
    runs-on: golang:1.15.15-buster
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build app
        run: |
          go build -o build/main
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
          if-no-files-found: error
          retention-days: 1

  publish:
    name: Publish docker image
    needs:
      - build
      - quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: debug
        run: ls -lR
      - name: Log in to Docker Hub
        uses: docker/login-action@1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@1
        with:
          images: sulfurf/litt
      - name: Build and push Docker image
        uses: docker/build-push-action@2
        with:
          context: .
          push: true
          tags: |
            sulfurf/litt:${{ github.sha }}
          labels: |
            sulfurf/litt:${{ github.sha }}
      

